corona/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from .forms import SignupForm
from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
    url(r'^$', views.home, name = "home"),        
    url(r'^stats/$', views.live_stat, name = "stats"),            
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/visit/(\d+)$', views.visitprofile, name='visitprofile'),
    url(r'^profile/edit/$', views.editprofile, name='editprofile'),
    url(r'^register/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate_account, name='activate'),
    url(r'^login/$', views.signIn, name='login'),     
    url(r'^patients_overview/$', views.patients_overview, name='panel'),
    url(r'contact/new/', views.profile, name = 'new-contact'),
    url(r'^doctor/verification/$', views.doc_su, name='doc_su'),
    url(r'^doctor/verification/confirm_doctor/(\d+)$', views.make_doctor, name='make_doctor'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

covid19/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'', include('corona.urls')),
    url('^', include('django.contrib.auth.urls')),
    url('admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),     
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

corona/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from django.utils import timezone

# Create your models here.
class User(AbstractUser):
    is_doctor = models.BooleanField(default=False, blank=True)
    is_staff = models.BooleanField(default=False, blank=True)
    
#Patient treatment option
class Treatment(models.Model):
    treatment = models.CharField(max_length=100)

    def __str__(self):
        return self.treatment

    @classmethod
    def get_treatment_default(cls,treatment_default):
        treatment = Treatment.filter(treatment__icontains=treatment_default)        
        return treatment

class Status(models.Model):
    status = models.CharField(max_length=100)

    def __str__(self):
        return self.status

    @classmethod
    def get_statement_default(cls,status_default):
        status = Status.filter(status__icontains=status_default)        
        return status.id

class Doctor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)                
    name = models.CharField(max_length=100)
    hospital = models.CharField(max_length=100)
    phone = models.CharField(max_length=10) 
    prof_pic = models.ImageField(upload_to = 'doctor/', blank=True) 
    post_date = models.DateTimeField(default=timezone.now)  

    def __str__(self):
        return self.name

    @property
    def photo_url(self):
        if self.prof_pic and hasattr(self.prof_pic, 'url'):
            return self.prof_pic.url

    def save_doctor(self):
        self.save()

    @classmethod
    def get_doc_profile(cls, id):
        profiles = Doctor.objects.filter(user=id)
        profile = profiles.order_by("-post_date").first()
        return profile

class Patient(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)                
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=10) 
    location = models.CharField(max_length=10) 
    nat_id = models.CharField(max_length=8) 
    prof_pic = models.ImageField(upload_to = 'patient/', blank=True, null=True) 
    post_date = models.DateTimeField(default=timezone.now)         
    def __str__(self):
        return self.name

    @property
    def photo_url(self):
        if self.prof_pic and hasattr(self.prof_pic, 'url'):
            return self.prof_pic.url
    
    @classmethod
    def get_pat_profile(cls, id):
        profiles = Patient.objects.filter(user=id)
        profile = profiles.order_by("-post_date").first()
        return profile

#Doctor report on a patient
class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)                
    comments = HTMLField(blank= True)
    temp = models.IntegerField()
    kit = models.CharField(max_length=100)
    status = models.ForeignKey(Status,on_delete=models.CASCADE, blank=True)    
    treatment = models.ForeignKey(Treatment,on_delete=models.CASCADE, blank=True)    
    doctor = models.ForeignKey(Doctor,on_delete=models.CASCADE, blank=True)         
    post_date = models.DateTimeField(default=timezone.now)        
        
    def __str__(self):
        return self.user

    @classmethod
    def get_report(cls,id):
        reports = Report.objects.filter(user=id)
        report = reports.order_by("-post_date").first()
        return report


class Contact(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)                
    name = models.CharField(max_length=25)
    email = models.CharField(max_length=25)
    phone = models.CharField(max_length=25)
    location = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    def save_contact(self):
        self.save()

    def delete_contact(self):
        self.delete()

corona/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .models import User, Report, Patient, Doctor, Contact
from material import Layout, Row

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200)

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
                        
    class Meta:
        model = User
        fields = ('username', 'username', 'password1', 'password2')
        

class LoginForm(AuthenticationForm):    
    class Meta:
        model = User
        fields = ['username', 'password']        

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        exclude = ["user","doctor","post_date"]

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        exclude = ["user","post_date"]

class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        exclude = ["user","post_date"]

class ContactForm(forms.ModelForm):
    class Meta:
        model= Contact 
        exclude  = ["user"]
    

corona/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignupForm, LoginForm, ReportForm, DoctorForm, PatientForm, ContactForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.contrib.auth.views import login as auth_login
from .models import User, Patient, Doctor, Contact
from django.contrib.auth import get_user_model
from .models import Treatment, Status, Report, Patient, Doctor, Contact, User
from django.http import HttpResponseRedirect
import requests
from django.conf import settings
from django.contrib import messages

User = get_user_model()
import requests

# Create your views here.
def home(request):    
    title = "Covid Index Bootstrap Test"
    current_user = request.user
    
    return render(request, 'index.html', {"title": title, "current_user":current_user})

def live_stat(request):
    current_user = request.user
    cov_response = requests.get('https://api.thevirustracker.com/free-api?countryTotals=ALL')
    cov_data = cov_response.json()
    ref_data = cov_data['countryitems'][0]
    
    return render(request, 'home.html', {"cov_data": ref_data, "current_user":current_user})

def signIn(request):
    msg = []
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        
        if user is not None:
            if user.is_active:
                login(request, user)
                if user.is_doctor:
                    return redirect('home')
                else:
                    return redirect('home')   
            else:
                msg.append('You account has been deactivated!')
    else:
        msg.append('Invalid Login credentials, try again!')
    form = LoginForm()
    return render(request, 'registration/login.html', {'form': form,'errors': msg})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            client = form.save(commit=False)
            client.is_active = False
            client.save()
            current_site = get_current_site(request)
            email_subject = 'Activate Your Account'
            message = render_to_string('acc_active_email.html', {
                'user': client,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(client.pk)).decode(),
                'token': account_activation_token.make_token(client),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(email_subject, message, to=[to_email])
            email.send()
            return HttpResponse('We have sent you an email, please confirm your email address to complete registration')
    else:
        form = SignupForm()
    return render( request, 'registration/registration_form.html', {'form': form} )

def activate_account(request, uidb64, token):
    title = 'CovTracker'
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)       
        return redirect('editprofile')
    else:
        return HttpResponse('Activation link is invalid!')

@login_required(login_url='/accounts/login/')
def profile(request):
    current_user = request.user    
    contactform=ContactForm() 
    reportform = ReportForm()      
    if current_user.is_doctor == True:
        profile = Doctor.get_doc_profile(current_user)
        doctor = Doctor.objects.filter(user=current_user).first()
        patient_report = Report.objects.filter(doctor=doctor).all()    

        return render(request, 'doctorprofile.html', {"profile": profile, "current_user": current_user,"patient_report":patient_report})

    else:
        profile = Patient.get_pat_profile(current_user)
        patient_report = Report.get_report(current_user) 
        contacts = Contact.objects.filter(user=current_user).all()
        endpoint =  'http://api.ipstack.com/check?access_key={api_key}&format=1'
        url = endpoint.format(api_key=settings.GEO_API_KEY)
        response = requests.get(url)
        geodata = response.json() 
        google_api = settings.GOOGLE_API_KEY         

        if request.method =='POST':
            contactform=ContactForm(request.POST)
            if contactform.is_valid():
                contact= contactform.save(commit=False)
                contact.user = current_user
                contact.save()        
            return redirect('profile')
        else:
            contactform=ContactForm()       
        return render(request, 'patientprofile.html', {"profile": profile, "current_user": current_user,"patient_report":patient_report,"contacts":contacts,"contactform":contactform,"reportform":reportform,'city': geodata['city'],
        'country': geodata['country_name'],
        'latitude': geodata['latitude'],
        'longitude': geodata['longitude'],
        'api_key': google_api})

@login_required(login_url='/accounts/login/')
def visitprofile(request,id):
    current_user = request.user       
    contactform = ContactForm()       
    if current_user.is_doctor == True:
        profile = Patient.objects.filter(user=id).first()
        doctor = Doctor.objects.filter(user=current_user).first()
        contacts = Contact.objects.filter(user=id).all()   
        patient_report = Report.get_report(id)
        

        if request.method == 'POST':
            reportform = ReportForm(request.POST)
            if reportform.is_valid():
                report = reportform.save(commit=False)
                report.user = profile.user
                report.doctor = doctor
                report.save()
            return render(request, 'patientprofile.html', {"profile": profile, "current_user": current_user, "reportform":reportform,"contactform":contactform, "patient_report":patient_report,"contacts":contacts})
        else:
            reportform = ReportForm()
            
        return render(request, 'patientprofile.html', {"profile": profile, "current_user": current_user, "reportform":reportform,"contactform":contactform, "patient_report":patient_report, "contacts":contacts})


@login_required(login_url='/accounts/login/')
def editprofile(request):
    current_user = request.user          
    if current_user.is_doctor == True:
        profile = Doctor.get_doc_profile(current_user)
        if request.method == 'POST':        
            form = DoctorForm(request.POST,request.FILES)
            if form.is_valid():
                add = form.save(commit=False)
                add.user = current_user            
                add.save()
            return redirect('profile')
        else:           
            form = DoctorForm()        
        return render(request, 'profile_edit.html', {"current_user": current_user, "form":form,"profile":profile})
    
    else:
        profile = Patient.get_pat_profile(current_user)
        if request.method == 'POST':        
            form = PatientForm(request.POST,request.FILES)            
            if form.is_valid():
                update = form.save(commit=False)
                update.user = current_user            
                update.save()
            return redirect('profile')
        else:           
            form = PatientForm()        
        return render(request, 'profile_edit.html', {"current_user": current_user, "form":form,"profile":profile})


@login_required(login_url='/accounts/login/')
def patients_overview(request):
    current_user = request.user
    title = "Covid Tracker - Patients Overview"
    if current_user.is_doctor:
        patients = Patient.objects.all()        

        return render(request, 'patients_overview.html', {"title": title, "patients": patients,"current_user":current_user})
    else:
        return redirect(home)

def doc_su(request):
    current_user = request.user
    if current_user.is_staff:
        users = User.objects.filter(is_doctor = False).filter(is_staff = False).order_by('-id').all()

        doctors = User.objects.filter(is_doctor = True).all()

        title = "Covid-Tracker: Doctor Verification"

        return render(request, 'doctor_verification.html', {"title": title, "users": users,"current_user":current_user, "doctors": doctors})
    else:
        return redirect(home)

def make_doctor(request, user_id):
    current_user = request.user

    if current_user.is_staff:
        user = User.objects.get(id = user_id)
        user.is_doctor = True
        user.save()
        name = user.username
        messages.success(request, r'' + name + ' has successfully been confirmed as a doctor')

        return redirect(doc_su)
    
    else:
        messages.warning(request, 'You do not have permission to perform this function')
        return redirect(doc_su)

corona/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

corona/templates/base.html
{% load bootstrap4 %}
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Covid-19 Tracker</title>
    {% endif %}
    
    {% block styles %}
        {% bootstrap_css %}        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">        
        <link href='https://fonts.googleapis.com/css?family=Russo+One' rel='stylesheet'>
        <link href="https://fonts.googleapis.com/css2?family=Grenze+Gotisch:wght@300&display=swap" rel="stylesheet">
    {% endblock %}
</head>
<body>
    {% block content %}

    {% endblock %}
    
    {% block scripts %}
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        {% bootstrap_javascript %}
    {% endblock %}
    <style>
        /* Logo styling start */   
        .heading-image {
          display: inline-block;  
          width:50px; 
          height:50px;              
        }
        .heading-word {      
          display: inline-block; 
          font-family: 'Russo One';              
          background: #373B44;  /* fallback for old browsers */
          background: -webkit-linear-gradient(to left, #4286f4, #373B44);  /* Chrome 10-25, Safari 5.1-6 */
          background: linear-gradient(to left, #4286f4, #373B44); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
          background-clip: text;                
          text-decoration-color: transparent;
          -webkit-background-clip: text;
          -moz-background-clip: text;
          -webkit-text-fill-color: transparent; 
          -moz-text-fill-color: transparent;
          -webkit-text-stroke: 0.03em white;                
        }
        /* Logo styling end */   
        .body{
            height: 100vh;
            width: 100%;
        }   
    </style>    
</body>
</html>

corona/templates/patientprofile.html
{% extends 'base.html' %}

<!-- Page styling-->
  {% load bootstrap4 %}
  {% load static %}
  {% include 'material/includes/material_css.html' %}
  {% include 'material/includes/material_js.html' %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  
  <!-- Page script-->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{%static 'js/main.js'%}"></script>
  {% block javascript %}
        <script>
          $(document).ready(function(){
            $('#profile-form').submit(function(event){
              event.preventDefault()
            //   form = $("#profile-form")
              console.log('hi')
              $.ajax({
                url:'/profile/',
                type:'POST',
                data:{
                    name:$('#id_name').val(),
                    email:$("#id_email").val(),
                    phone:$('#id_phone').val(),
                    location:$("#id_location").val(),
                },
                success: function(){
                    console.log('name')
                },
                dataType:'json',
                
              })// END of Ajax method
              
            }) // End of submit event
          
          }) // End of document ready function
        </script>
        {% bootstrap_javascript %}
      {% endblock %} 
  {% block content %}
  {{block.super}}
    <!-- Add navigation Bar-->
    {% include "navbar.html" %}
      <!--Main row -->
      <div class="row">          

        <div class="col-md-2"><!--Empty column to center the profile--> </div>      
          <div class="col-md-8" style="background: #b1e8fb77;"> 
              
            <!-- Profile Picture-->
            <div class="container" style="margin-top: 30px; text-align: center;">                
                <img src="{{ profile.photo_url|default_if_none:'https://icon-library.net/images/patient-icon/patient-icon-25.jpg' }}" alt="profile picture" style=" width:225px; height: 225px; border-radius:50%;">                                
                {% if current_user.is_doctor %}
                  <!-- If you're a doctor you get nothing-->
                {% else %}
                  <a href="{% url 'editprofile' %}"><button style="display: inline-block;" class="btn btn-primary">Update Profile</button></a>                  
                {% endif %}
            </div>
            
            <!-- Name and email of profile -->
            <div class="container" style="margin-left: 12%; margin-top: 30px;">
                <h6 style="display: inline-block; padding-right: 15%;">Name: <span style="font-size: 20px;">{{profile.name}}</span></h6>
                <h6 style="display: inline-block;">Email: <span style="font-size: 20px;">{{profile.user.email}}</span></h6>
            </div>
                            
            <!-- Profile details i.e Phone,location, their status, prefered treatment-->
            <h6 style="display: inline-block;margin-left: 15%; padding-right:15%;">Phone no.: <span style="font-size: 20px;">{{profile.phone}}</span></h6>
            <h6 style="display: inline-block;">Status: <span style="font-size: 20px;">{{patient_report.status}}</span></h6>            
            <h6 style="display: inline-block;margin-left: 15%; padding-right:15%;">Location: <span style="font-size: 20px;">{{profile.location}}</span></h6>
            <h6 style="display: inline-block;">Treatment: <span style="font-size: 20px;">{{patient_report.treatment}}</span></h6>            
              
              
              <div class="row" style="margin-top: 30px;">

                <!-- Patient live location cordinates on a map -->
                <div class="col">
                  {% if current_user.is_doctor %}
                  {% else %}
                  <div class="col" id="map">                    
                    <!-- User location map -->
                    <p>Your are in <strong>{{ city }}</strong>,<strong>{{ country }}</strong> based on your ip address.</p>
                    <iframe 
                          frameborder="0"
                         style="border:0; width:100%; height:100%; object-fit: cover;"
                         src="https://www.google.com/maps/embed/v1/view?center={{ latitude }},{{ longitude }}&zoom=8&key={{ api_key }}"
                         allowfullscreen>
                    </iframe>
                  </div>
                  {% endif %}
                </div>

                <!-- Doctors report section-->
                <div class="col">
                  <div class="container" style="background:white;">

                    <!-- The section heading and if condition to allow only doctors to access the input button -->
                    <div class="container" style="padding: 10px;">
                      <h5 style="text-align: center; color: blue; display: inline-block; padding-right: 30%;">Doctor's report</h5>  
                      {% if current_user.is_doctor %}
                        <button class="btn btn-primary" style="display: inline-block;" data-toggle="modal" data-target="#reportform" >Add Report</button>                      
                      {% else %}
                      {% endif %}
                    </div>  
                    
                    <!-- Report table-->              
                    <table class="table table-hover">                                                    
                          <tbody>                                                    
                            <tr>                                
                              <td colspan="3" style="font-weight: bold;">Temperature</td>                                
                              {% if patient_report.temp %}
                              <td> {{patient_report.temp}} °C</td>
                              {% else %}
                              <td>--°C</td>                            
                              {% endif %}
                            </tr>
                            <tr>
                              <td colspan="3" style="font-weight: bold;">Test No.</td>                                                                
                              {% if patient_report.kit %}
                              <td> {{patient_report.kit}}</td>
                              {% else %}
                              <td>----</td>                            
                              {% endif %}
                            </tr>         
                            <tr>
                              <td style="font-weight: bold;">Comment</td>                                
                              {% if patient_report.comments %}
                                <td colspan="4">
                                  {{patient_report.comments | safe}}
                                  <p style="font-size: 12px; color: grey; margin-left: 60%;">Dr. {{patient_report.doctor}}</p>
                                </td>
                              {% else %}
                                <td colspan="4"> No comments yet.</td>
                              {% endif %}
                            </tr>                                               
                          </tbody>                                                                        
                    </table>
                    
                  </div>
                </div>

                <!-- Edit Health Report Modal -->
                <div class="modal fade" id="reportform" tabindex="-1" role="dialog" aria-labelledby="reportform" aria-hidden="true" >
                  <div class="modal-dialog modal-lg modal-dialog-centered" role="document"  style="background:url('https://images.unsplash.com/photo-1581299327801-faeb40ea459e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1171&q=80')">
                    <div class="modal-content" style="background:white;" >
                      <div class="modal-header">
                        <h4 class="modal-title" style="margin-left: 40%;">Doctor's Report</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div> 
                      <div class="modal-body">
                        <div class="container" style="text-align: center; width:80%;">
                          <form action="{% url 'visitprofile' profile.user.id %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                        
                            {% bootstrap_form reportform %}
                            <input type="submit" class="btn btn-success btn-lg" value="Update report">
                          </form> 
                        </div>
                      </div>    
                    </div>
                  </div>
                </div>

              </div> 

              <!-- Contact tracing section -->
              <div class="container" style="background: white; margin-top:5vh;">
                <div class="container">
                  <div class="row">  
                    
                    <!-- Contact tracing table -->
                    <table class="table">
                      <thead class="thead-dark">
                        <tr>                            
                          <th scope="col">Name</th>
                          <th scope="col">Email</th>
                          <th scope="col">Phone</th>
                          <th scope="col">Location</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for cont in contacts %}
                        <tr>                            
                          <td>{{cont.name}}</td>
                          <td>{{cont.email}}</td>
                          <td>{{cont.phone}}</td>
                          <td>{{cont.location}}</td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>   

                  </div>

                  <!-- Contact tracing form -->
                  <div class="row">
                    {% if current_user.is_doctor %}
                      <!-- If you're a doctor you get nothing-->
                    {% else %}
                      <!-- Patient get's a form to fill their contacts-->
                      <div class="col-md-6 col-md-offset-3">
                        <form action="{% url 'profile' %}" method='post' enctype="multipart/form-data" id="profile-form">
                          {% csrf_token %}
                        
                          {% bootstrap_form contactform %}
                            <input type="submit" class="btn btn-sucess" value="Post">
                        </form>                                            
                      </div>

                    {% endif %}
                  </div>
                </div>
              </div>            
          </div>
        <div class="col"><!-- Empty col to center the profile--></div>
      </div>  
       
  
  {% endblock %}
  